### ISSUE TITLE
Getting error in ruby-sdk 2.0.1.

### ISSUE THREAD

**Issue by t-wata-cldt** [square/connect-api-specification#15]
I'm getting following error message when I installed version 2.0.1 with bundler.
2.0.0 works fine so seems like require of `models.*` is causing this.
Any clues?
```
/Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/square_connect-2.0.1/lib/square_connect.rb:20:in `require': cannot load such file -- models.Address (LoadError)
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/square_connect-2.0.1/lib/square_connect.rb:20:in `<top (required)>'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
	from /Users/takeshi/Documents/telework_center/config/application.rb:7:in `<top (required)>'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/takeshi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by tristansokol** [comment]
Hmm, that doesn't seem right. Would you mind sharing some of the code you ran to get to that error?

**Comment by t-wata-cldt** [comment]
What I did was add
```ruby
gem 'square_connect'
```
to Gemfile and `bundle install` it, then `bundle exec rails g migration`.
I'm getting this before getting to do something.

**Comment by tristansokol** [comment]
Are you getting this error during `bundle install`? I deally you would see something more like:
```
~/Desktop/scratch bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing ffi 1.9.17 with native extensions
Installing json 1.8.6 with native extensions
Using bundler 1.13.4
Using ethon 0.10.1
Using typhoeus 0.8.0
Using square_connect 2.0.1
Bundle complete! 1 Gemfile dependency, 6 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.```

**Comment by t-wata-cldt** [comment]
Nope. The `bundle install` ends fine.
At least what I got from the error message is that It's failing in rails' bundled gem loading phase.
I don't know there is a gem that handles `models.Address` style of `require`.

**Comment by jawspeak** [comment]
believe this is fixed in https://github.com/square/connect-api-specification/pull/16
